import { useQuery } from '@tanstack/react-query';
import { api } from '../../api';
import type { Page as ApiPage, Project, Workspace } from '../../api';
import { Field } from '../../components/atoms/Field';
import { healthOptions } from '../../utils/healthOptions';
import { priorityOptions } from '../../utils/priorityOptions';

export function FlowProperties({ workspace, flow, save }: { workspace: Workspace; flow: any; save: (body: any) => void }) {
  const projects = useQuery<ApiPage<Project>>({ queryKey: ['project-options', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/projects?limit=100`) }); const members = useQuery<any[]>({ queryKey: ['members', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/members`) });
  return <details className="properties"><summary>Manage flow</summary><form className="property-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); save({ name: form.get('name'), priority: form.get('priority'), health: form.get('health'), responsibleMembershipId: form.get('responsibleMembershipId') || null, primaryCurrentTaskId: form.get('primaryCurrentTaskId') || null, scope: form.get('scope'), allowedProjectIds: Array.from((event.currentTarget.elements.namedItem('allowedProjectIds') as HTMLSelectElement).selectedOptions).map((option) => option.value) }); }}><Field label="Name" name="name" defaultValue={flow.name} required /><label>Priority<select name="priority" defaultValue={flow.priority}>{priorityOptions()}</select></label><label>Health<select name="health" defaultValue={flow.health}>{healthOptions()}</select></label><label>Responsible member<select name="responsibleMembershipId" defaultValue={flow.responsibleMembershipId ?? ''}><option value="">No responsible member</option>{members.data?.filter((member) => member.active).map((member) => <option key={member.id} value={member.id}>{member.displayName}</option>)}</select></label><label>Primary current task<select name="primaryCurrentTaskId" defaultValue={flow.primaryCurrentTaskId ?? ''}><option value="">No primary task</option>{flow.tasks?.map((entry: any) => <option key={entry.task.id} value={entry.task.id}>{entry.task.title}</option>)}</select></label><label>Project scope<select name="scope" defaultValue={flow.scope}><option value="all_projects">All projects</option><option value="selected_projects">Selected projects</option></select></label><label>Allowed projects<select name="allowedProjectIds" multiple defaultValue={flow.allowedProjects?.map((project: Project) => project.id) ?? []}>{projects.data?.items.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><button className="button primary" type="submit">Save flow details</button></form></details>;
}
