import { useEffect, useState } from 'react';
import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, mutation, type Workspace } from '../../api';
import { Empty } from '../../components/molecules/Empty';
import { Page } from '../../components/templates/Page';
import { RetrievalAdmin } from './RetrievalAdmin';
import { TracePanel } from './TracePanel';
import { retrievalIntents, retrievalSourceTypes, type Job, type Profile, type RetrievalAdminTab, type SearchResponse } from './types';
import { useCursorList } from '../../hooks/useCursorList';

export function RetrievalPage({ workspace }: { workspace: Workspace }) {
  const client = useQueryClient(); const [projectId, setProjectId] = useState(''); const [query, setQuery] = useState(''); const [intent, setIntent] = useState(''); const [historical, setHistorical] = useState(false); const [expand, setExpand] = useState(true); const [selectedTypes, setSelectedTypes] = useState<string[]>([]); const [response, setResponse] = useState<SearchResponse | null>(null); const [selectedIndex, setSelectedIndex] = useState(0); const [adminTab, setAdminTab] = useState<RetrievalAdminTab>('profiles');
  const projects = useCursorList<any>(['retrieval-projects', workspace.id], `/workspaces/${workspace.id}/projects`, {});
  useEffect(() => { if (!projectId && projects.items[0]) setProjectId(projects.items[0].id); }, [projectId, projects.items]);
  const profiles = useQuery<Profile[]>({ queryKey: ['retrieval-profiles', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/retrieval/embedding-profiles`) });
  const activeProfile = profiles.data?.find((profile) => profile.active) ?? profiles.data?.[0];
  const jobs = useInfiniteQuery<{ items: Job[]; total: number; nextOffset: number | null }>({ queryKey: ['retrieval-jobs', workspace.id, projectId], initialPageParam: 0, queryFn: ({ pageParam }) => api(`/workspaces/${workspace.id}/retrieval/embedding-jobs?projectId=${projectId}&limit=100&offset=${pageParam}`), getNextPageParam: (page) => page.nextOffset ?? undefined, enabled: Boolean(projectId) });
  const documents = useInfiniteQuery<{ items: any[]; total: number; nextOffset: number | null }>({ queryKey: ['retrieval-documents', workspace.id, projectId, activeProfile?.key], initialPageParam: 0, queryFn: ({ pageParam }) => api(`/workspaces/${workspace.id}/retrieval/documents?projectId=${projectId}&embeddingProfileKey=${encodeURIComponent(activeProfile!.key)}&limit=100&offset=${pageParam}`), getNextPageParam: (page) => page.nextOffset ?? undefined, enabled: Boolean(projectId && activeProfile?.key) });
  const jobItems = jobs.data?.pages.flatMap((page) => page.items) ?? []; const documentItems = documents.data?.pages.flatMap((page) => page.items) ?? []; const missing = documentItems.filter((entry) => !entry.embeddingPresent);
  const search = useMutation({ mutationFn: () => api<SearchResponse>(`/workspaces/${workspace.id}/retrieval/search`, mutation('POST', { query, projectId, sourceTypes: selectedTypes, intent: intent || undefined, includeHistorical: historical, expandRelatedTasks: expand, embeddingProfileKey: activeProfile?.key, limit: 20 })), onSuccess: (data) => { setResponse(data); setSelectedIndex(0); } });
  const refresh = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/retrieval/refresh`, mutation('POST', { projectId })), onSuccess: () => { client.invalidateQueries({ queryKey: ['retrieval-jobs', workspace.id] }); client.invalidateQueries({ queryKey: ['retrieval-missing', workspace.id] }); } });
  const result = response?.results[selectedIndex];
  const toggleType = (value: string) => setSelectedTypes((current) => current.includes(value) ? current.filter((entry) => entry !== value) : [...current, value]);
  return <Page heading="Retrieval" subheading="Search current and historical project memory with ranked provenance and inspectable traces." action={<button className="button" disabled={!projectId || refresh.isPending} onClick={() => refresh.mutate()}>{refresh.isPending ? 'Refreshing…' : 'Refresh index'}</button>}>
    <section className="retrieval-console"><div className="retrieval-query"><input className="search large" aria-label="Semantic search query" placeholder="Ask what the project knows…" value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && query.trim().length > 1 && search.mutate()} /><button className="button primary" disabled={!projectId || query.trim().length < 2 || search.isPending} onClick={() => search.mutate()}>{search.isPending ? 'Searching…' : 'Search memory'}</button></div><div className="retrieval-filters"><select value={projectId} onChange={(event) => setProjectId(event.target.value)}>{projects.items.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><select value={intent} onChange={(event) => setIntent(event.target.value)}><option value="">Auto intent</option>{retrievalIntents.map((value) => <option key={value}>{value.replaceAll('_', ' ')}</option>)}</select><label className="check"><input type="checkbox" checked={historical} onChange={(event) => setHistorical(event.target.checked)} /> Historical</label><label className="check"><input type="checkbox" checked={expand} onChange={(event) => setExpand(event.target.checked)} /> Related tasks</label></div>{projects.hasNextPage ? <button className="text-button" onClick={() => void projects.fetchNextPage()}>Load more projects</button> : null}<div className="source-chips">{retrievalSourceTypes.map((value) => <button key={value} className={selectedTypes.includes(value) ? 'active' : ''} onClick={() => toggleType(value)}>{value.replaceAll('_', ' ')}</button>)}</div></section>
    {response ? <div className="control-workbench retrieval-workbench"><aside className="control-list"><div className="control-list-heading"><span>{response.results.length} ranked results</span><span>{response.intent.replaceAll('_', ' ')}</span></div>{response.results.map((entry, index) => <button key={`${entry.document.id}-${index}`} className={`retrieval-row ${index === selectedIndex ? 'selected' : ''}`} onClick={() => setSelectedIndex(index)}><span className="rank">{index + 1}</span><span><strong>{entry.document.title}</strong><small>{entry.document.sourceType.replaceAll('_', ' ')} · {entry.document.status}</small><p>{entry.document.content.slice(0, 180)}</p></span><b>{entry.score.toFixed(3)}</b></button>)}</aside><section className="control-detail">{result && <><header className="control-detail-header"><div><span className="eyebrow">{result.document.sourceType.replaceAll('_', ' ')} · rank {selectedIndex + 1}</span><h2>{result.document.title}</h2><p>{result.document.contextualPrefix}</p></div><strong className="score-badge">{result.score.toFixed(3)}</strong></header><div className="score-strip">{Object.entries(result.scores).map(([key, value]) => <div key={key}><small>{key}</small><strong>{value.toFixed(3)}</strong><i style={{ width: `${Math.max(2, Math.min(100, value * 100))}%` }} /></div>)}</div><section className="inspector-section"><h3>Retrieved content</h3><div className="retrieved-content">{result.document.content}</div></section><section className="inspector-section"><h3>Authority and provenance</h3><dl className="inspector-dl"><div><dt>Authority</dt><dd>{(result.document.authorityBasisPoints / 100).toFixed(0)}%</dd></div><div><dt>Status</dt><dd>{result.document.status}</dd></div><div><dt>Sensitivity</dt><dd>{result.document.sensitivity}</dd></div><div><dt>Source ID</dt><dd><code>{result.document.sourceId}</code></dd></div><div><dt>Task</dt><dd><code>{result.document.taskId ?? '—'}</code></dd></div><div><dt>Recorded</dt><dd>{new Date(result.document.sourceRecordedAt).toLocaleString()}</dd></div></dl></section><TracePanel workspace={workspace} traceId={response.trace.id} summary={response.trace} /></>}</section></div> : <Empty title="Search durable project memory" text="Choose a project and ask a precise question. Every result retains its source and scoring trace." />}
    <RetrievalAdmin workspace={workspace} projectId={projectId} tab={adminTab} setTab={setAdminTab} profiles={profiles.data ?? []} jobs={jobItems} jobTotal={jobs.data?.pages[0]?.total ?? 0} loadMoreJobs={jobs.hasNextPage ? () => void jobs.fetchNextPage() : undefined} documents={documentItems} documentTotal={documents.data?.pages[0]?.total ?? 0} loadMoreDocuments={documents.hasNextPage ? () => void documents.fetchNextPage() : undefined} missing={missing} activeProfile={activeProfile} />
  </Page>;
}
