import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api, type Workspace } from '../../api';
import type { SearchResponse } from './types';

export function TracePanel({ workspace, traceId, summary }: { workspace: Workspace; traceId: string; summary: SearchResponse['trace'] }) {
  const [open, setOpen] = useState(false);
  const trace = useQuery<any>({ queryKey: ['retrieval-trace', workspace.id, traceId], queryFn: () => api(`/workspaces/${workspace.id}/retrieval/traces/${traceId}`), enabled: open });
  const data = trace.data ?? summary; const counts = data.candidateCounts ?? {}; const scoring = data.scoring ?? {};
  return <section className="inspector-section trace-panel"><button className="section-header trace-toggle" onClick={() => setOpen(!open)}><span><h3>Retrieval trace</h3><small>{summary.semanticUsed ? 'Hybrid semantic + lexical' : 'Lexical fallback'} · {traceId}</small></span><span>{open ? 'Hide' : 'Inspect'}</span></button>{open ? <div className="trace-structure"><div className="fact-strip"><div><small>Mode</small><strong>{data.semanticUsed ? 'Hybrid' : 'Lexical'}</strong></div><div><small>Intent</small><strong>{data.intent ?? 'inferred'}</strong></div><div><small>Created</small><strong>{data.createdAt ? new Date(data.createdAt).toLocaleString() : '—'}</strong></div><div><small>Trace ID</small><strong>{traceId.slice(0, 8)}</strong></div></div><h4>Candidate funnel</h4><div className="trace-flow">{Object.entries(counts).map(([key, value], index) => <div key={key}><span>{index + 1}</span><strong>{key.replaceAll('_', ' ')}</strong><b>{String(value)}</b></div>)}</div><h4>Scoring configuration</h4><dl className="inspector-dl">{Object.entries(scoring).map(([key, value]) => <div key={key}><dt>{key.replaceAll('_', ' ')}</dt><dd>{typeof value === 'object' ? Object.entries(value as Record<string, unknown>).map(([nested, nestedValue]) => `${nested}: ${String(nestedValue)}`).join(' · ') : String(value)}</dd></div>)}</dl>{data.filters ? <><h4>Applied filters</h4><dl className="inspector-dl">{Object.entries(data.filters).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{Array.isArray(value) ? value.join(', ') : String(value)}</dd></div>)}</dl></> : null}</div> : null}</section>;
}
