import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Navigate, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import DOMPurify from 'dompurify';
import { marked } from 'marked';
import { api, ApiError, Flow, mutation, Project, setCsrfToken, Task, User, WorkflowState, Workspace } from './api';

type Session = { user: User; csrfToken: string };
const nav = [{ to: 'tasks', label: 'Tasks', mark: 'T' }, { to: 'projects', label: 'Projects', mark: 'P' }, { to: 'flows', label: 'Flows', mark: 'F' }];

function App() {
  const session = useQuery<Session>({ queryKey: ['session'], queryFn: () => api('/auth/me'), retry: false });
  useEffect(() => { if (session.data?.csrfToken) setCsrfToken(session.data.csrfToken); }, [session.data]);
  if (session.isLoading) return <Loading />;
  if (!session.data) return <Access />;
  return <AuthedApp session={session.data} />;
}

function Access() {
  const setup = useQuery<{ initialized: boolean }>({ queryKey: ['setup-status'], queryFn: () => api('/auth/setup-status') });
  if (setup.isLoading) return <Loading />;
  return <main className="access"><section className="access-card"><Brand /><h1>{setup.data?.initialized ? 'Welcome back' : 'Set up your control room'}</h1><p>{setup.data?.initialized ? 'Sign in to continue where the work is.' : 'Create the first administrator and workspace.'}</p>{setup.data?.initialized ? <Login /> : <Setup />}</section></main>;
}

function Login() {
  const client = useQueryClient(); const [error, setError] = useState('');
  const action = useMutation({ mutationFn: (body: any) => api<Session>('/auth/login', mutation('POST', body)), onSuccess: (data) => { setCsrfToken(data.csrfToken); client.setQueryData(['session'], data); }, onError: (err: ApiError) => setError(err.message) });
  return <form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); action.mutate({ email: form.get('email'), password: form.get('password') }); }} className="stack"><Field label="Email" name="email" type="email" required autoComplete="email" /><Field label="Password" name="password" type="password" required autoComplete="current-password" /><Error text={error} /><button className="button primary" disabled={action.isPending}>{action.isPending ? 'Signing in…' : 'Sign in'}</button></form>;
}

function Setup() {
  const client = useQueryClient(); const [error, setError] = useState('');
  const action = useMutation({ mutationFn: (body: any) => api<Session>('/auth/setup', mutation('POST', body)), onSuccess: (data) => { setCsrfToken(data.csrfToken); client.setQueryData(['session'], data); }, onError: (err: ApiError) => setError(err.message) });
  return <form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); action.mutate(Object.fromEntries(form)); }} className="stack"><Field label="Your name" name="displayName" required /><Field label="Email" name="email" type="email" required /><Field label="Password" name="password" type="password" required minLength={12} /><Field label="First workspace" name="workspaceName" required /><Field label="Setup token" name="setupToken" type="password" required /><Error text={error} /><button className="button primary" disabled={action.isPending}>{action.isPending ? 'Creating…' : 'Create Anklav'}</button></form>;
}

function AuthedApp({ session }: { session: Session }) {
  const workspaces = useQuery<Workspace[]>({ queryKey: ['workspaces'], queryFn: () => api('/workspaces'), refetchInterval: 15_000 });
  const [theme, setTheme] = useState(localStorage.getItem('anklav-theme') ?? 'system');
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('anklav-theme', theme); }, [theme]);
  if (workspaces.isLoading) return <Loading />;
  if (!workspaces.data?.length) return <CreateFirstWorkspace />;
  return <Routes>
    <Route path="/" element={<Navigate to={`/w/${workspaces.data[0]!.id}/tasks`} replace />} />
    <Route path="/w/:workspaceId/*" element={<WorkspaceShell session={session} workspaces={workspaces.data} theme={theme} setTheme={setTheme} />} />
    <Route path="*" element={<Navigate to={`/w/${workspaces.data[0]!.id}/tasks`} replace />} />
  </Routes>;
}

function CreateFirstWorkspace() {
  const client = useQueryClient(); const [name, setName] = useState('');
  const create = useMutation({ mutationFn: () => api('/workspaces', mutation('POST', { name })), onSuccess: () => client.invalidateQueries({ queryKey: ['workspaces'] }) });
  return <main className="access"><section className="access-card"><Brand /><h1>Create a workspace</h1><p>Workspaces are your isolated portfolios. You will be its first owner.</p><form className="stack" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><Field label="Workspace name" value={name} onChange={setName} /><button className="button primary">Create workspace</button></form></section></main>;
}

function WorkspaceShell({ session, workspaces, theme, setTheme }: { session: Session; workspaces: Workspace[]; theme: string; setTheme: (next: string) => void }) {
  const { workspaceId = '' } = useParams(); const navigate = useNavigate(); const current = workspaces.find((workspace) => workspace.id === workspaceId) ?? workspaces[0]!;
  if (current.id !== workspaceId) return <Navigate to={`/w/${current.id}/tasks`} replace />;
  return <div className="app-shell"><aside className="sidebar"><Brand compact /><label className="workspace-select"><span>Workspace</span><select value={current.id} onChange={(event) => navigate(`/w/${event.target.value}/tasks`)}>{workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select></label><nav>{nav.map((item) => <NavLink key={item.to} to={`/w/${current.id}/${item.to}`} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`}><b>{item.mark}</b>{item.label}</NavLink>)}<NavLink to={`/w/${current.id}/settings`} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`}><b>⚙</b>Settings</NavLink></nav><div className="sidebar-footer"><button className="text-button" onClick={() => setTheme(theme === 'dark' ? 'light' : theme === 'light' ? 'system' : 'dark')}>Theme: {theme}</button><span>{session.user.displayName}</span></div></aside><main className="workspace-main"><ChangePoller workspaceId={current.id} /><Routes><Route path="tasks/:taskId?" element={<TasksPage workspace={current} />} /><Route path="projects/:projectId?" element={<ProjectsPage workspace={current} />} /><Route path="flows/:flowId?" element={<FlowsPage workspace={current} />} /><Route path="settings/*" element={<SettingsPage workspace={current} />} /><Route path="*" element={<Navigate to="tasks" replace />} /></Routes></main></div>;
}

function ChangePoller({ workspaceId }: { workspaceId: string }) {
  const client = useQueryClient(); const [after, setAfter] = useState(() => Number(sessionStorage.getItem(`anklav-sequence-${workspaceId}`) ?? 0));
  const changes = useQuery<any[]>({ queryKey: ['changes', workspaceId, after], queryFn: () => api(`/workspaces/${workspaceId}/changes?after=${after}`), refetchInterval: 15_000, retry: false });
  useEffect(() => { if (!changes.data?.length) return; const next = Math.max(...changes.data.map((entry) => Number(entry.sequence))); sessionStorage.setItem(`anklav-sequence-${workspaceId}`, String(next)); setAfter(next); client.invalidateQueries({ predicate: (query) => Array.isArray(query.queryKey) && query.queryKey.includes(workspaceId) && query.queryKey[0] !== 'changes' }); }, [changes.data, client, workspaceId]);
  return null;
}

function TasksPage({ workspace }: { workspace: Workspace }) {
  const { taskId } = useParams(); const navigate = useNavigate(); const [q, setQ] = useState('');
  const tasks = useQuery<any[]>({ queryKey: ['tasks', workspace.id, q], queryFn: () => api(`/workspaces/${workspace.id}/tasks?q=${encodeURIComponent(q)}`), refetchInterval: 15_000 });
  const projects = useQuery<Project[]>({ queryKey: ['projects', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/projects`) });
  const states = useQuery<WorkflowState[]>({ queryKey: ['states', workspace.id, 'task'], queryFn: () => api(`/workspaces/${workspace.id}/workflows?entity=task`) });
  return <Page heading="Tasks" subheading="Bounded work with a clear technical home." action={<CreateTask workspace={workspace} projects={projects.data ?? []} states={states.data ?? []} />}><div className="content-grid"><section className="list-panel"><input className="search" placeholder="Search tasks" value={q} onChange={(event) => setQ(event.target.value)} />{tasks.isLoading ? <Loading /> : <div className="table-list">{tasks.data?.map((row) => <button key={row.task.id} onClick={() => navigate(`/w/${workspace.id}/tasks/${row.task.id}`)} className={`row-button ${taskId === row.task.id ? 'selected' : ''}`}><Status state={row.state} /><span className="row-main"><strong>{row.task.title}</strong><small>{row.project.name} · {row.task.priority}</small></span><time>{relativeTime(row.task.updatedAt)}</time></button>)}</div>}{!tasks.data?.length && <Empty title="No tasks yet" text="Capture the next bounded piece of work." />}</section><section className="detail-panel">{taskId ? <TaskDetail workspace={workspace} taskId={taskId} states={states.data ?? []} /> : <Hint title="Choose a task" text="Open a task to see its purpose, criteria, evidence, and history." />}</section></div></Page>;
}

function CreateTask({ workspace, projects, states }: { workspace: Workspace; projects: Project[]; states: WorkflowState[] }) {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [projectId, setProjectId] = useState(projects[0]?.id ?? '');
  useEffect(() => { if (!projectId && projects[0]) setProjectId(projects[0].id); }, [projectId, projects]);
  const action = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/tasks`, mutation('POST', { title, projectId, workflowStateId: states.find((state) => state.isInitial)?.id })), onSuccess: () => { client.invalidateQueries({ queryKey: ['tasks', workspace.id] }); setOpen(false); setTitle(''); } });
  if (!open) return <button className="button primary" disabled={!projects.length} onClick={() => setOpen(true)}>New task</button>;
  return <InlineForm onCancel={() => setOpen(false)} onSubmit={() => action.mutate()} pending={action.isPending}><Field label="Title" value={title} onChange={setTitle} autoFocus /><label>Project<select value={projectId} onChange={(event) => setProjectId(event.target.value)}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><Error text={action.error instanceof Error ? action.error.message : ''} /></InlineForm>;
}

function TaskDetail({ workspace, taskId, states }: { workspace: Workspace; taskId: string; states: WorkflowState[] }) {
  const client = useQueryClient(); const detail = useQuery<any>({ queryKey: ['task', workspace.id, taskId], queryFn: () => api(`/workspaces/${workspace.id}/tasks/${taskId}`), refetchInterval: 15_000 }); const [comment, setComment] = useState('');
  const update = useMutation({ mutationFn: (body: any) => api(`/workspaces/${workspace.id}/tasks/${taskId}`, mutation('PATCH', body, detail.data.version)), onSuccess: () => client.invalidateQueries({ queryKey: ['task', workspace.id, taskId] }), onError: (err: ApiError) => err.status === 412 && client.invalidateQueries({ queryKey: ['task', workspace.id, taskId] }) });
  const review = useMutation({ mutationFn: (reviewStatus: string) => api(`/workspaces/${workspace.id}/tasks/${taskId}/review`, mutation('PATCH', { reviewStatus }, detail.data.version)), onSuccess: () => client.invalidateQueries({ queryKey: ['task', workspace.id, taskId] }) });
  const commentAction = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/task/${taskId}/comments`, mutation('POST', { body: comment })), onSuccess: () => { setComment(''); client.invalidateQueries({ queryKey: ['task', workspace.id, taskId] }); } });
  if (detail.isLoading) return <Loading />; if (!detail.data) return <Empty title="Task not found" text="It may have been deleted or moved." />;
  const task = detail.data;
  const chooseState = async (workflowStateId: string) => { const preview = await api<{ warnings: string[] }>(`/workspaces/${workspace.id}/tasks/${taskId}/transition-preview?stateId=${workflowStateId}`); if (!preview.warnings.length || window.confirm(`This transition has advisory signals:\n\n${preview.warnings.join('\n')}\n\nContinue?`)) update.mutate({ workflowStateId }); };
  return <article className="detail"><header className="detail-header"><div><span className="eyebrow">{task.project?.name}</span><h2>{task.title}</h2></div><select aria-label="Task state" value={task.workflowStateId} onChange={(event) => void chooseState(event.target.value)}>{states.map((state) => <option key={state.id} value={state.id}>{state.name}</option>)}</select></header>{task.transitionWarnings?.length > 0 && <Callout title="Transition signals">{task.transitionWarnings.map((warning: string) => <p key={warning}>{warning}</p>)}</Callout>}<EditableMarkdown title="Goal and scope" value={task.description} onSave={(description) => update.mutate({ description })} /><section className="meta-grid"><Meta label="Priority" value={task.priority} />{task.humanReviewRequired ? <label>Human review<select value={task.reviewStatus} onChange={(event) => review.mutate(event.target.value)}><option value="pending">pending</option><option value="approved">approved</option><option value="changes_requested">changes requested</option></select></label> : <Meta label="Human review" value="Not required" />}<Meta label="Due" value={task.dueDate ?? '—'} /></section><Checklist workspace={workspace} task={task} /><EditableMarkdown title="Completion evidence" value={task.completionEvidence} empty="Record verification, evidence, limits, and follow-up work." onSave={(completionEvidence) => update.mutate({ completionEvidence })} /><section><h3>Flows</h3>{task.flows?.length ? task.flows.map((entry: any) => <span className="chip" key={entry.flow.id}>{entry.link.role}: {entry.flow.name}</span>) : <p className="muted">Not connected to a flow.</p>}</section><section><h3>Discussion</h3><div className="comments">{task.comments?.map((entry: any) => <article key={entry.id} className="comment"><Markdown value={entry.body} /><small>{relativeTime(entry.createdAt)}</small></article>)}</div><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add progress, evidence, or a question…" /><button className="button" disabled={!comment.trim() || commentAction.isPending} onClick={() => commentAction.mutate()}>Add comment</button></section><Activity events={task.activity ?? []} /></article>;
}

function Checklist({ workspace, task }: { workspace: Workspace; task: any }) {
  const client = useQueryClient(); const [text, setText] = useState(''); const [kind, setKind] = useState<'readiness' | 'acceptance'>('acceptance');
  const add = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/tasks/${task.id}/checklists`, mutation('POST', { text, kind })), onSuccess: () => { setText(''); client.invalidateQueries({ queryKey: ['task', workspace.id, task.id] }); } });
  const toggle = useMutation({ mutationFn: (item: any) => api(`/workspaces/${workspace.id}/checklists/${item.id}`, mutation('PATCH', { completed: !item.completed })), onSuccess: () => client.invalidateQueries({ queryKey: ['task', workspace.id, task.id] }) });
  return <section><h3>Criteria</h3>{['readiness', 'acceptance'].map((group) => <div className="criteria" key={group}><h4>{group === 'readiness' ? 'Readiness' : 'Acceptance'}</h4>{task.checklists?.filter((item: any) => item.kind === group).map((item: any) => <label className="check" key={item.id}><input type="checkbox" checked={item.completed} onChange={() => toggle.mutate(item)} />{item.text}</label>)}</div>)}<div className="inline-fields"><select value={kind} onChange={(event) => setKind(event.target.value as any)}><option value="acceptance">Acceptance</option><option value="readiness">Readiness</option></select><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Add criterion" /><button className="button" onClick={() => add.mutate()} disabled={!text.trim()}>Add</button></div></section>;
}

function ProjectsPage({ workspace }: { workspace: Workspace }) {
  const { projectId } = useParams(); const navigate = useNavigate(); const projects = useQuery<Project[]>({ queryKey: ['projects', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/projects`), refetchInterval: 15_000 });
  return <Page heading="Projects" subheading="Stable technical ownership boundaries." action={<CreateProject workspace={workspace} />}><div className="content-grid"><section className="list-panel"><div className="table-list">{projects.data?.map((project) => <button key={project.id} onClick={() => navigate(`/w/${workspace.id}/projects/${project.id}`)} className={`row-button ${projectId === project.id ? 'selected' : ''}`}><span className="project-mark">P</span><span className="row-main"><strong>{project.name}</strong><small>{project.status} · {project.health.replace('_', ' ')}</small></span><time>{relativeTime(project.updatedAt)}</time></button>)}</div>{!projects.data?.length && <Empty title="No projects yet" text="Create the technical home for a stream of work." />}</section><section className="detail-panel">{projectId ? <ProjectDetail workspace={workspace} projectId={projectId} /> : <Hint title="Choose a project" text="Projects stay stable even as priorities and flows change." />}</section></div></Page>;
}

function CreateProject({ workspace }: { workspace: Workspace }) {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [name, setName] = useState('');
  const create = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/projects`, mutation('POST', { name })), onSuccess: () => { client.invalidateQueries({ queryKey: ['projects', workspace.id] }); setOpen(false); setName(''); } });
  return open ? <InlineForm onCancel={() => setOpen(false)} onSubmit={() => create.mutate()} pending={create.isPending}><Field label="Project name" value={name} onChange={setName} autoFocus /></InlineForm> : <button className="button primary" onClick={() => setOpen(true)}>New project</button>;
}

function ProjectDetail({ workspace, projectId }: { workspace: Workspace; projectId: string }) {
  const client = useQueryClient(); const detail = useQuery<any>({ queryKey: ['project', workspace.id, projectId], queryFn: () => api(`/workspaces/${workspace.id}/projects/${projectId}`) });
  const update = useMutation({ mutationFn: (body: any) => api(`/workspaces/${workspace.id}/projects/${projectId}`, mutation('PATCH', body, detail.data.version)), onSuccess: () => { client.invalidateQueries({ queryKey: ['project', workspace.id, projectId] }); client.invalidateQueries({ queryKey: ['projects', workspace.id] }); } });
  if (detail.isLoading) return <Loading />; if (!detail.data) return <Empty title="Project not found" text="It may have been deleted." />; const project = detail.data;
  return <article className="detail"><header className="detail-header"><div><span className="eyebrow">Technical ownership</span><h2>{project.name}</h2></div><select value={project.status} onChange={(event) => update.mutate({ status: event.target.value })}>{['proposed', 'planned', 'active', 'paused', 'completed', 'archived'].map((status) => <option key={status}>{status}</option>)}</select></header><EditableMarkdown title="Purpose" value={project.description} onSave={(description) => update.mutate({ description })} /><section className="meta-grid"><label>Priority<select value={project.priority} onChange={(event) => update.mutate({ priority: event.target.value })}>{priorityOptions()}</select></label><label>Health<select value={project.health} onChange={(event) => update.mutate({ health: event.target.value })}>{healthOptions()}</select></label></section><EditableMarkdown title="Current focus" value={project.currentFocus} onSave={(currentFocus) => update.mutate({ currentFocus })} /><section><h3>Work in this project</h3>{project.tasks?.length ? project.tasks.slice(0, 12).map((task: Task) => <p key={task.id} className="linked-row">{task.title}</p>) : <p className="muted">No active tasks.</p>}</section><section><h3>Flows involving this project</h3>{project.flows?.length ? project.flows.map((flow: Flow) => <span className="chip" key={flow.id}>{flow.name}</span>) : <p className="muted">No connected flows.</p>}</section><Activity events={project.activity ?? []} /></article>;
}

function FlowsPage({ workspace }: { workspace: Workspace }) {
  const { flowId } = useParams(); const navigate = useNavigate(); const flows = useQuery<any[]>({ queryKey: ['flows', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/flows`), refetchInterval: 15_000 }); const states = useQuery<WorkflowState[]>({ queryKey: ['states', workspace.id, 'flow'], queryFn: () => api(`/workspaces/${workspace.id}/workflows?entity=flow`) });
  return <Page heading="Flows" subheading="Persistent continuity of purpose across projects." action={<CreateFlow workspace={workspace} states={states.data ?? []} />}><div className="content-grid"><section className="list-panel"><div className="table-list">{flows.data?.map(({ flow, state }) => <button key={flow.id} onClick={() => navigate(`/w/${workspace.id}/flows/${flow.id}`)} className={`row-button ${flowId === flow.id ? 'selected' : ''}`}><Status state={state} /><span className="row-main"><strong>{flow.name}</strong><small>{state.name} · {flow.health.replace('_', ' ')}</small></span><time>{relativeTime(flow.updatedAt)}</time></button>)}</div>{!flows.data?.length && <Empty title="No flows yet" text="Define a persistent direction before every task is known." />}</section><section className="detail-panel">{flowId ? <FlowDetail workspace={workspace} flowId={flowId} states={states.data ?? []} /> : <Hint title="Choose a flow" text="Flows make strategic intent visible across project boundaries." />}</section></div></Page>;
}

function CreateFlow({ workspace, states }: { workspace: Workspace; states: WorkflowState[] }) {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [name, setName] = useState('');
  const create = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/flows`, mutation('POST', { name, workflowStateId: states.find((state) => state.isInitial)?.id })), onSuccess: () => { client.invalidateQueries({ queryKey: ['flows', workspace.id] }); setOpen(false); setName(''); } });
  return open ? <InlineForm onCancel={() => setOpen(false)} onSubmit={() => create.mutate()} pending={create.isPending}><Field label="Flow name" value={name} onChange={setName} autoFocus /></InlineForm> : <button className="button primary" onClick={() => setOpen(true)}>New flow</button>;
}

function FlowDetail({ workspace, flowId, states }: { workspace: Workspace; flowId: string; states: WorkflowState[] }) {
  const client = useQueryClient(); const detail = useQuery<any>({ queryKey: ['flow', workspace.id, flowId], queryFn: () => api(`/workspaces/${workspace.id}/flows/${flowId}`), refetchInterval: 15_000 }); const [criterion, setCriterion] = useState('');
  const update = useMutation({ mutationFn: (body: any) => api(`/workspaces/${workspace.id}/flows/${flowId}`, mutation('PATCH', body, detail.data.version)), onSuccess: () => { client.invalidateQueries({ queryKey: ['flow', workspace.id, flowId] }); client.invalidateQueries({ queryKey: ['flows', workspace.id] }); } });
  const addCriterion = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/flows/${flowId}/criteria`, mutation('POST', { text: criterion })), onSuccess: () => { setCriterion(''); client.invalidateQueries({ queryKey: ['flow', workspace.id, flowId] }); } });
  const updateCriterion = useMutation({ mutationFn: (item: any) => api(`/workspaces/${workspace.id}/criteria/${item.id}`, mutation('PATCH', { completed: !item.completed })), onSuccess: () => client.invalidateQueries({ queryKey: ['flow', workspace.id, flowId] }) });
  if (detail.isLoading) return <Loading />; if (!detail.data) return <Empty title="Flow not found" text="It may have been deleted." />; const flow = detail.data;
  const chooseState = async (workflowStateId: string) => { const preview = await api<{ warnings: string[] }>(`/workspaces/${workspace.id}/flows/${flowId}/transition-preview?stateId=${workflowStateId}`); if (!preview.warnings.length || window.confirm(`This transition has advisory signals:\n\n${preview.warnings.join('\n')}\n\nContinue?`)) update.mutate({ workflowStateId }); };
  return <article className="detail"><header className="detail-header"><div><span className="eyebrow">Continuity of purpose</span><h2>{flow.name}</h2></div><select value={flow.workflowStateId} onChange={(event) => void chooseState(event.target.value)}>{states.map((state) => <option key={state.id} value={state.id}>{state.name}</option>)}</select></header>{flow.signals?.transitionWarnings?.length > 0 && <Callout title="Convergence signals">{flow.signals.transitionWarnings.map((warning: string) => <p key={warning}>{warning}</p>)}</Callout>}<EditableMarkdown title="Purpose" value={flow.purpose} onSave={(purpose) => update.mutate({ purpose })} /><section><h3>Convergence criteria <small>{flow.signals?.criteria?.completed ?? 0}/{flow.signals?.criteria?.total ?? 0}</small></h3>{flow.criteria?.map((item: any) => <label className="check" key={item.id}><input type="checkbox" checked={item.completed} onChange={() => updateCriterion.mutate(item)} />{item.text}</label>)}<div className="inline-fields"><input value={criterion} onChange={(event) => setCriterion(event.target.value)} placeholder="Add convergence criterion" /><button className="button" onClick={() => addCriterion.mutate()} disabled={!criterion.trim()}>Add</button></div></section><EditableMarkdown title="Current focus" value={flow.currentFocus} onSave={(currentFocus) => update.mutate({ currentFocus })} /><EditableMarkdown title="Next recommended action" value={flow.nextRecommendedAction} onSave={(nextRecommendedAction) => update.mutate({ nextRecommendedAction })} /><section><h3>Participating projects</h3>{flow.participatingProjects?.map((project: Project) => <span className="chip" key={project.id}>{project.name}</span>) ?? <p className="muted">Tasks will derive participating projects.</p>}</section><section><h3>Tasks by project</h3>{flow.tasks?.map((entry: any) => <p className="linked-row" key={entry.task.id}><span className="chip">{entry.project.name}</span> {entry.task.title}</p>)}</section><Activity events={flow.activity ?? []} /></article>;
}

function SettingsPage({ workspace }: { workspace: Workspace }) {
  const states = useQuery<WorkflowState[]>({ queryKey: ['states', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/workflows`) }); const labels = useQuery<any[]>({ queryKey: ['labels', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/labels`) }); const members = useQuery<any[]>({ queryKey: ['members', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/members`) }); const trash = useQuery<any>({ queryKey: ['trash', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/trash`) }); const client = useQueryClient(); const [labelName, setLabelName] = useState('');
  const addLabel = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/labels`, mutation('POST', { name: labelName })), onSuccess: () => { setLabelName(''); client.invalidateQueries({ queryKey: ['labels', workspace.id] }); } });
  return <Page heading="Settings" subheading="Workspace membership, workflows, labels, and recovery."><div className="settings-grid"><section className="settings-card"><h2>Workflow states</h2>{states.data?.map((state) => <div className="setting-row" key={state.id}><Status state={state} /><span>{state.entityType} · {state.taskSemantic ?? state.flowSemantic}</span><small>{state.position + 1}</small></div>)}<p className="muted">Admins may extend and reorder these lifecycle states through the API; seeded semantic categories remain stable.</p></section><section className="settings-card"><h2>Labels</h2>{labels.data?.map((label) => <div className="setting-row" key={label.id}><span className="label-dot" style={{ background: label.color }} /><span>{label.name}</span></div>)}<div className="inline-fields"><input value={labelName} onChange={(event) => setLabelName(event.target.value)} placeholder="New label" /><button className="button" onClick={() => addLabel.mutate()} disabled={!labelName.trim()}>Add</button></div></section><section className="settings-card"><h2>Members</h2>{members.data?.map((member) => <div className="setting-row" key={member.id}><span><strong>{member.displayName}</strong><small>{member.email}</small></span><span className="chip">{member.role}</span></div>)}</section><section className="settings-card"><h2>Trash</h2>{trash.data && Object.values(trash.data).flat().length ? <p className="muted">{Object.values(trash.data).flat().length} deleted records are recoverable through the API.</p> : <p className="muted">Nothing is currently deleted.</p>}</section></div></Page>;
}

function Page({ heading, subheading, action, children }: { heading: string; subheading: string; action?: ReactNode; children: ReactNode }) { return <div className="page"><header className="page-header"><div><span className="eyebrow">Anklav control room</span><h1>{heading}</h1><p>{subheading}</p></div><div className="page-action">{action}</div></header>{children}</div>; }
function Brand({ compact = false }: { compact?: boolean }) { return <div className={`brand ${compact ? 'compact' : ''}`}><span className="brand-mark">N</span>{!compact && <span>Anklav</span>}</div>; }
function Field({ label, name, type = 'text', value, onChange, ...props }: { label: string; name?: string; type?: string; value?: string; onChange?: (value: string) => void; [key: string]: any }) { return <label className="field"><span>{label}</span><input name={name} type={type} value={value} onChange={onChange ? (event) => onChange(event.target.value) : undefined} {...props} /></label>; }
function InlineForm({ children, onSubmit, onCancel, pending }: { children: ReactNode; onSubmit: () => void; onCancel: () => void; pending: boolean }) { return <form className="inline-form" onSubmit={(event) => { event.preventDefault(); onSubmit(); }}>{children}<div><button className="button primary" disabled={pending}>Create</button><button type="button" className="button ghost" onClick={onCancel}>Cancel</button></div></form>; }
function Status({ state }: { state: Partial<WorkflowState> }) { return <span className="status-dot" title={state.name} style={{ background: state.color ?? '#64748b' }} />; }
function Meta({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><strong>{value}</strong></div>; }
function Callout({ title, children }: { title: string; children: ReactNode }) { return <aside className="callout"><strong>{title}</strong>{children}</aside>; }
function Activity({ events }: { events: any[] }) { return <section><h3>Activity</h3>{events.length ? <ol className="activity">{events.slice(0, 20).map((event) => <li key={event.id}><strong>{event.action.replaceAll('_', ' ')}</strong><small>{relativeTime(event.createdAt)}</small></li>)}</ol> : <p className="muted">No activity recorded yet.</p>}</section>; }
function Markdown({ value }: { value: string }) { const html = useMemo(() => DOMPurify.sanitize(marked.parse(value || '') as string), [value]); return value ? <div className="markdown" dangerouslySetInnerHTML={{ __html: html }} /> : null; }
function EditableMarkdown({ title, value, empty = 'Add context.', onSave }: { title: string; value: string; empty?: string; onSave: (value: string) => void }) { const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(value); useEffect(() => setDraft(value), [value]); return <section><header className="section-header"><h3>{title}</h3><button className="text-button" onClick={() => editing ? (onSave(draft), setEditing(false)) : setEditing(true)}>{editing ? 'Save' : 'Edit'}</button></header>{editing ? <textarea autoFocus value={draft} onChange={(event) => setDraft(event.target.value)} placeholder={empty} /> : <Markdown value={value} />}{!editing && !value && <p className="muted">{empty}</p>}</section>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><strong>{title}</strong><p>{text}</p></div>; }
function Hint({ title, text }: { title: string; text: string }) { return <div className="hint"><span>↗</span><h2>{title}</h2><p>{text}</p></div>; }
function Error({ text }: { text: string }) { return text ? <p className="error">{text}</p> : null; }
function Loading() { return <div className="loading"><span />Loading…</div>; }
function priorityOptions() { return ['none', 'low', 'medium', 'high', 'urgent'].map((value) => <option value={value} key={value}>{value}</option>); }
function healthOptions() { return ['unknown', 'on_track', 'at_risk', 'off_track'].map((value) => <option value={value} key={value}>{value.replace('_', ' ')}</option>); }
function relativeTime(value: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1_000)); if (seconds < 60) return 'now'; if (seconds < 3_600) return `${Math.floor(seconds / 60)}m`; if (seconds < 86_400) return `${Math.floor(seconds / 3_600)}h`; return `${Math.floor(seconds / 86_400)}d`; }

export default App;
