import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { api, mutation, type Project, type Workspace } from '../../api';
import { ControlDrawer } from '../../components/organisms/ControlDrawer';
import { artifactTypes } from './types';

export function ArtifactComposer({ workspace, projects, flows, tasks, close, done }: { workspace: Workspace; projects: Project[]; flows: any[]; tasks: any[]; close: () => void; done: () => void }) {
  const [git, setGit] = useState(false); const create = useMutation({ mutationFn: (body: any) => api(`/workspaces/${workspace.id}/knowledge-artifacts`, mutation('POST', body)), onSuccess: done });
  return <ControlDrawer title="Record artifact" close={close}><form className="drawer-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ projectId: form.get('projectId') || null, flowId: form.get('flowId') || null, taskId: form.get('taskId') || null, type: git ? 'git_reference' : form.get('type'), title: form.get('title'), summary: form.get('summary'), ...(git ? { repositoryReference: { repositoryFullName: form.get('repository'), path: form.get('path'), commitSha: form.get('commit') || null, contentHash: form.get('contentHash') || null, githubRepositoryId: form.get('githubRepositoryId') || null, verificationNote: form.get('verificationNote') || '' } } : { nativeContent: form.get('content') }) }); }}><label>Project<select name="projectId"><option value="">Workspace-wide</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Flow<select name="flowId"><option value="">No flow</option>{flows.map((flow) => <option key={flow.id} value={flow.id}>{flow.name}</option>)}</select></label><label>Task<select name="taskId"><option value="">No task</option>{tasks.map((task) => <option key={task.id} value={task.id}>{task.identifier} · {task.title}</option>)}</select></label><label className="check"><input type="checkbox" checked={git} onChange={(event) => setGit(event.target.checked)} /> Git-backed immutable source</label>{!git && <label>Type<select name="type">{artifactTypes.filter((value) => value !== 'git_reference').map((value) => <option key={value}>{value}</option>)}</select></label>}<label>Title<input name="title" required /></label><label>Summary<textarea name="summary" /></label>{git ? <><label>Repository<input name="repository" placeholder="owner/repository" required /></label><label>Path<input name="path" required /></label><label>Commit SHA<input name="commit" /></label><label>Content SHA-256<input name="contentHash" pattern="[a-f0-9]{64}" /></label><label>GitHub repository ID<input name="githubRepositoryId" /></label><label>Verification note<textarea name="verificationNote" /></label></> : <label>Native content<textarea name="content" required /></label>}<button className="button primary">Record artifact</button></form></ControlDrawer>;
}
