import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { api, mutation, type Workspace } from '../../api';
import type { Milestone } from './types';

export function MilestoneInspector({ workspace, item, refresh }: { workspace: Workspace; item: Milestone; refresh: () => void }) {
  const detail = useQuery<Milestone>({ queryKey: ['milestone', workspace.id, item.id], queryFn: () => api(`/workspaces/${workspace.id}/milestones/${item.id}`) });
  const milestone = detail.data ?? item; const [edit, setEdit] = useState(false);
  const update = useMutation({ mutationFn: (body: any) => api(`/workspaces/${workspace.id}/milestones/${milestone.id}`, mutation('PATCH', body, milestone.version)), onSuccess: () => { setEdit(false); refresh(); detail.refetch(); } });
  const remove = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/milestones/${milestone.id}`, mutation('DELETE', undefined, milestone.version)), onSuccess: refresh });
  return <><header className="control-detail-header"><div><span className="eyebrow">Milestone · {milestone.status}</span><h2>{milestone.name}</h2><p>{milestone.description || 'No description.'}</p></div><div className="button-row"><button className="button" onClick={() => setEdit(!edit)}>{edit ? 'Cancel' : 'Edit'}</button><button className="button danger" onClick={() => window.confirm('Move this milestone to trash?') && remove.mutate()}>Delete</button></div></header><div className="fact-strip"><div><small>Status</small><strong>{milestone.status.replaceAll('_', ' ')}</strong></div><div><small>Target</small><strong>{milestone.targetDate ?? 'Unscheduled'}</strong></div><div><small>Tasks</small><strong>{milestone.tasks?.length ?? 0}</strong></div><div><small>Flow</small><strong>{milestone.flowId ? 'Linked' : 'Project-wide'}</strong></div></div>{edit && <form className="inspector-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); update.mutate({ name: form.get('name'), description: form.get('description'), status: form.get('status'), targetDate: form.get('targetDate') || null }); }}><input name="name" defaultValue={milestone.name} required /><textarea name="description" defaultValue={milestone.description} /><select name="status" defaultValue={milestone.status}>{['planned', 'in_progress', 'completed', 'cancelled', 'archived'].map((value) => <option key={value}>{value}</option>)}</select><input name="targetDate" type="date" defaultValue={milestone.targetDate ?? ''} /><button className="button primary">Save milestone</button></form>}<section className="inspector-section"><h3>Linked tasks</h3>{milestone.tasks?.length ? milestone.tasks.map((task) => <p key={task.id} className="linked-row"><strong>{task.identifier}</strong> {task.title}</p>) : <p className="muted">No tasks linked to this milestone.</p>}</section></>;
}
