import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, mutation } from '../../api';
import type { Page as ApiPage, Project, Workspace } from '../../api';
import { Error } from '../../components/atoms/Error';

export function GitHubSettings({ workspace }: { workspace: Workspace }) {
  const client = useQueryClient(); const connection = useQuery<any>({ queryKey: ['github', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/github`), retry: false }); const projects = useQuery<ApiPage<Project>>({ queryKey: ['github-projects', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/projects?limit=100`) });
  const [organizationLogin, setOrganizationLogin] = useState(''); const [repositoryId, setRepositoryId] = useState(''); const [projectId, setProjectId] = useState(''); const [syncMode, setSyncMode] = useState('none');
  const connect = useMutation({ mutationFn: () => api<{ redirectUrl: string }>(`/workspaces/${workspace.id}/github/manifest`, mutation('POST', { organizationLogin })), onSuccess: ({ redirectUrl }) => window.location.assign(redirectUrl) });
  const account = useMutation({ mutationFn: () => api<{ redirectUrl: string }>(`/workspaces/${workspace.id}/github/account`, mutation('POST')), onSuccess: ({ redirectUrl }) => window.location.assign(redirectUrl) });
  const map = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/github/repositories/mappings`, mutation('POST', { repositoryId, projectId, syncMode, defaultInbound: syncMode !== 'none', defaultOutbound: syncMode === 'bidirectional' })), onSuccess: () => client.invalidateQueries({ queryKey: ['github', workspace.id] }) });
  if (connection.isLoading) return <section className="settings-card"><h2>GitHub</h2><p className="muted">Loading connection status…</p></section>;
  if (connection.data?.enabled === false) return <section className="settings-card"><h2>GitHub</h2><p className="muted">GitHub integration is disabled by this instance. Set GITHUB_INTEGRATION_ENABLED=true, PUBLIC_BASE_URL, and INTEGRATION_ENCRYPTION_KEY to enable it.</p></section>;
  const repositories = connection.data?.repositories ?? [];
  return <section className="settings-card wide"><h2>GitHub</h2>{!connection.data?.connection ? <div className="stack"><p className="muted">Create a private GitHub App for one organization. Anklav will retain its credentials encrypted in this workspace database.</p><div className="inline-fields"><input value={organizationLogin} onChange={(event) => setOrganizationLogin(event.target.value)} placeholder="GitHub organization" /><button className="button primary" disabled={!organizationLogin.trim() || connect.isPending} onClick={() => connect.mutate()}>Create GitHub App</button></div><Error text={connect.error instanceof Error ? connect.error.message : ''} /></div> : <div className="stack"><p><span className="chip">{connection.data.connection.status}</span> {connection.data.connection.organizationLogin ?? 'Organization pending'}</p><div className="inline-fields"><button className="button" onClick={() => account.mutate()} disabled={account.isPending}>Connect my GitHub account</button></div>{repositories.length ? <form className="property-form" onSubmit={(event) => { event.preventDefault(); map.mutate(); }}><label>Repository<select value={repositoryId} onChange={(event) => setRepositoryId(event.target.value)} required><option value="">Choose…</option>{repositories.map((repository: any) => <option key={repository.id} value={repository.id}>{repository.fullName}</option>)}</select></label><label>Project<select value={projectId} onChange={(event) => setProjectId(event.target.value)} required><option value="">Choose…</option>{projects.data?.items.map((project) => <option key={project.id} value={project.id}>{project.issueKey} · {project.name}</option>)}</select></label><label>Issue sync<select value={syncMode} onChange={(event) => setSyncMode(event.target.value)}><option value="none">PR linking only</option><option value="inbound">GitHub → Anklav</option><option value="bidirectional">Two-way issue sync</option></select></label><button className="button primary" disabled={map.isPending}>Save mapping</button></form> : <p className="muted">Install the GitHub App to load its selected repositories.</p>}<Error text={account.error instanceof Error ? account.error.message : map.error instanceof Error ? map.error.message : ''} /></div>}</section>;
}
