import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, mutation, Workspace } from '../../api';
import { Error } from '../../components/atoms/Error';

export function TaskGitHub({ workspace, task }: { workspace: Workspace; task: any }) {
  const client = useQueryClient(); const [repositoryId, setRepositoryId] = useState(''); const [branch, setBranch] = useState('');
  const connection = useQuery<any>({ queryKey: ['github', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/github`), retry: false });
  const branchAction = useMutation({ mutationFn: () => api<{ branch: string }>(`/workspaces/${workspace.id}/github/tasks/${task.identifier}/branch`), onSuccess: async (result) => { setBranch(result.branch); await navigator.clipboard?.writeText(result.branch); } });
  const createIssue = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/github/tasks/${task.identifier}/issues`, mutation('POST', { repositoryId, syncMode: 'manual' })), onSuccess: () => client.invalidateQueries({ queryKey: ['task', workspace.id, task.identifier] }) });
  const repositories = connection.data?.repositories ?? [];
  useEffect(() => { if (!repositoryId && repositories[0]) setRepositoryId(repositories[0].id); }, [repositoryId, repositories]);
  return <section className="github-card"><header className="section-header"><h3>GitHub</h3><span className="chip">{connection.data?.connection?.status ?? (connection.data?.enabled === false ? 'disabled' : 'not connected')}</span></header><div className="inline-fields"><button className="button" onClick={() => branchAction.mutate()} disabled={!connection.data?.connection}>Copy branch name</button>{branch && <code>{branch}</code>}</div>{task.githubIssues?.length ? <div className="github-links">{task.githubIssues.map((issue: any) => <a key={issue.id} href={issue.htmlUrl} target="_blank" rel="noreferrer">Issue #{issue.issueNumber} · {issue.syncStatus}</a>)}</div> : connection.data?.connection ? <div className="inline-fields"><select value={repositoryId} onChange={(event) => setRepositoryId(event.target.value)}><option value="">Choose repository…</option>{repositories.map((repository: any) => <option key={repository.id} value={repository.id}>{repository.fullName}</option>)}</select><button className="button" disabled={!repositoryId || createIssue.isPending} onClick={() => createIssue.mutate()}>Create GitHub issue</button></div> : <p className="muted">Connect GitHub in workspace settings to copy a branch name, link issues, and track pull requests.</p>}<Error text={branchAction.error instanceof Error ? branchAction.error.message : createIssue.error instanceof Error ? createIssue.error.message : ''} />{task.githubPullRequests?.length ? <div className="github-links">{task.githubPullRequests.map((entry: any) => <a key={entry.id} href={entry.pullRequest.htmlUrl} target="_blank" rel="noreferrer">PR #{entry.pullRequest.number} · {entry.pullRequest.state}</a>)}</div> : null}</section>;
}
