import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { api, mutation, type Workspace } from '../../api';
import { ControlDrawer } from '../../components/organisms/ControlDrawer';
import type { EvidenceRow } from './types';

const classifications = ['verified_current_fact', 'accepted_decision', 'evidence_backed_inference', 'hypothesis', 'obsolete_or_contradicted', 'human_decision_required'];

export function ClaimComposer({ workspace, projectId, evidence, close, done }: { workspace: Workspace; projectId: string; evidence: EvidenceRow[]; close: () => void; done: () => void }) {
  const [form, setForm] = useState({ subject: '', predicate: '', value: '', classification: 'evidence_backed_inference', confidence: '8000', evidenceId: evidence[0]?.artifact.id ?? '' }); const [error, setError] = useState('');
  const submit = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/memory/claims`, mutation('POST', { projectId, subject: form.subject, predicate: form.predicate, value: form.value, classification: form.classification, confidenceBasisPoints: Number(form.confidence), sourceEvidenceArtifactId: form.evidenceId, sourceSpan: {}, extraction: {} })), onSuccess: done, onError: (err: Error) => setError(err.message) });
  return <ControlDrawer eyebrow="Durable memory" title="Propose claim" close={close}><div className="drawer-form"><label>Subject<input value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} placeholder="Authentication service" /></label><label>Predicate<input value={form.predicate} onChange={(e) => setForm({ ...form, predicate: e.target.value })} placeholder="uses" /></label><label>Value<textarea value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} placeholder="Rotating refresh tokens" /></label><label>Classification<select value={form.classification} onChange={(e) => setForm({ ...form, classification: e.target.value })}>{classifications.map((value) => <option key={value}>{value}</option>)}</select></label><label>Confidence (basis points)<input type="number" min="0" max="10000" value={form.confidence} onChange={(e) => setForm({ ...form, confidence: e.target.value })} /></label><label>Source evidence<select value={form.evidenceId} onChange={(e) => setForm({ ...form, evidenceId: e.target.value })}><option value="">Choose exact evidence…</option>{evidence.map(({ artifact }) => <option key={artifact.id} value={artifact.id}>{artifact.title}</option>)}</select></label>{error && <p className="error">{error}</p>}<button className="button primary" disabled={!form.subject || !form.predicate || !form.value || !form.evidenceId || submit.isPending} onClick={() => submit.mutate()}>Propose claim</button></div></ControlDrawer>;
}
