import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { api, mutation, type Workspace } from '../../api';
import { ControlDrawer } from '../../components/organisms/ControlDrawer';
import type { EvidenceRow } from './types';

const splitLines = (value: string) => value.split('\n').map((entry) => entry.trim()).filter(Boolean);

export function DecisionComposer({ workspace, projectId, evidence, close, done }: { workspace: Workspace; projectId: string; evidence: EvidenceRow[]; close: () => void; done: () => void }) {
  const [form, setForm] = useState({ question: '', selectedOption: '', alternatives: '', rationale: '', consequences: '', evidenceIds: evidence[0]?.artifact.id ?? '', taskId: '', runId: '', repository: '', commit: '' }); const [error, setError] = useState('');
  const selectedEvidence = form.evidenceIds.split(',').map((value) => value.trim()).filter(Boolean);
  const submit = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/memory/decisions`, mutation('POST', { projectId, taskId: form.taskId || undefined, proposedByRunId: form.runId || undefined, question: form.question, selectedOption: form.selectedOption, rejectedAlternatives: splitLines(form.alternatives), rationale: form.rationale, consequences: splitLines(form.consequences), effectiveRepository: form.repository || undefined, effectiveFromCommit: form.commit || undefined, evidenceArtifactIds: selectedEvidence })), onSuccess: done, onError: (err: Error) => setError(err.message) });
  return <ControlDrawer eyebrow="Durable memory" title="Propose decision" close={close}><div className="drawer-form"><label>Question<input value={form.question} onChange={(e) => setForm({ ...form, question: e.target.value })} placeholder="How should session state be stored?" /></label><label>Selected option<input value={form.selectedOption} onChange={(e) => setForm({ ...form, selectedOption: e.target.value })} /></label><label>Rejected alternatives (one per line)<textarea value={form.alternatives} onChange={(e) => setForm({ ...form, alternatives: e.target.value })} /></label><label>Rationale<textarea value={form.rationale} onChange={(e) => setForm({ ...form, rationale: e.target.value })} /></label><label>Consequences (one per line)<textarea value={form.consequences} onChange={(e) => setForm({ ...form, consequences: e.target.value })} /></label><div className="form-grid"><label>Task scope<input value={form.taskId} onChange={(e) => setForm({ ...form, taskId: e.target.value })} /></label><label>Proposing run<input value={form.runId} onChange={(e) => setForm({ ...form, runId: e.target.value })} /></label><label>Effective repository<input value={form.repository} onChange={(e) => setForm({ ...form, repository: e.target.value })} placeholder="owner/repository" /></label><label>Effective commit<input value={form.commit} onChange={(e) => setForm({ ...form, commit: e.target.value })} /></label></div><label>Evidence artifacts (comma separated IDs)<textarea value={form.evidenceIds} onChange={(e) => setForm({ ...form, evidenceIds: e.target.value })} /></label><div className="source-chips">{evidence.map(({ artifact }) => <button key={artifact.id} type="button" className={selectedEvidence.includes(artifact.id) ? 'active' : ''} onClick={() => setForm({ ...form, evidenceIds: selectedEvidence.includes(artifact.id) ? selectedEvidence.filter((id) => id !== artifact.id).join(', ') : [...selectedEvidence, artifact.id].join(', ') })}>{artifact.title}</button>)}</div>{error && <p className="error">{error}</p>}<button className="button primary" disabled={!form.question || !form.selectedOption || !form.rationale || !selectedEvidence.length || submit.isPending} onClick={() => submit.mutate()}>Propose decision</button></div></ControlDrawer>;
}
