import type { Claim, Decision } from './types';

export function MemoryInspector({ item, kind, admin, allItems, onResolve, onSupersede }: { item: Claim | Decision; kind: 'claims' | 'decisions'; admin: boolean; allItems: (Claim | Decision)[]; onResolve: (action: 'accept' | 'reject') => void; onSupersede: (id: string) => void }) {
  const claim = kind === 'claims' ? item as Claim : null; const decision = kind === 'decisions' ? item as Decision : null;
  return <><header className="control-detail-header"><div><span className="eyebrow">{kind.slice(0, -1)} · {item.status}</span><h2>{claim ? `${claim.subject} ${claim.predicate}` : decision?.question}</h2><p>{claim?.value ?? decision?.selectedOption}</p></div>{admin && item.status === 'proposed' && <div className="button-row"><button className="button primary" onClick={() => onResolve('accept')}>Accept</button><button className="button danger" onClick={() => onResolve('reject')}>Reject</button></div>}</header>
    <div className="fact-strip">{claim ? <><div><small>Classification</small><strong>{claim.classification.replaceAll('_', ' ')}</strong></div><div><small>Confidence</small><strong>{(claim.confidenceBasisPoints / 100).toFixed(0)}%</strong></div><div><small>Validity</small><strong>{claim.validUntilAt || claim.validUntilCommit ? 'Historical' : 'Current'}</strong></div><div><small>Scope</small><strong>{claim.taskId ? 'Task' : 'Project'}</strong></div></> : <><div><small>Status</small><strong>{decision?.status}</strong></div><div><small>Repository</small><strong>{decision?.effectiveRepository ?? 'Project-wide'}</strong></div><div><small>From commit</small><strong>{decision?.effectiveFromCommit?.slice(0, 10) ?? 'Immediately'}</strong></div><div><small>Evidence</small><strong>{decision?.evidenceArtifactIds.length}</strong></div></>}</div>
    {decision && <><section className="inspector-section"><h3>Rationale</h3><p>{decision.rationale || 'No rationale recorded.'}</p></section><section className="inspector-section"><h3>Rejected alternatives</h3>{decision.rejectedAlternatives.map((value) => <p key={value} className="memory-alternative">{value}</p>) || <p className="muted">None recorded.</p>}<h3>Consequences</h3>{decision.consequences.map((value) => <p key={value}>• {value}</p>)}</section></>}
    <section className="inspector-section"><h3>Validity and provenance</h3><dl className="inspector-dl">{claim ? <><div><dt>From</dt><dd>{claim.validFromCommit ?? claim.validFromAt ?? 'recorded time'}</dd></div><div><dt>Until</dt><dd>{claim.validUntilCommit ?? claim.validUntilAt ?? 'current'}</dd></div><div><dt>Evidence</dt><dd><code>{claim.sourceEvidenceArtifactId ?? claim.sourceKnowledgeArtifactId}</code></dd></div></> : <><div><dt>Effective until</dt><dd>{decision?.effectiveUntilCommit ?? 'current'}</dd></div>{decision?.evidenceArtifactIds.map((id) => <div key={id}><dt>Evidence</dt><dd><code>{id}</code></dd></div>)}</>}</dl></section>
    {item.resolutionNote && <section className="inspector-section"><h3>Resolution</h3><p>{item.resolutionNote}</p></section>}
    {admin && item.status !== 'superseded' && <section className="inspector-section"><h3>Supersession</h3><select defaultValue="" onChange={(event) => event.target.value && onSupersede(event.target.value)}><option value="">Replace with another {kind.slice(0, -1)}…</option>{allItems.filter((other) => other.id !== item.id).map((other) => <option key={other.id} value={other.id}>{kind === 'claims' ? (other as Claim).value : (other as Decision).selectedOption}</option>)}</select></section>}
  </>;
}
