import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, mutation, type Workspace } from '../../api';
import { Page } from '../../components/templates/Page';
import { relativeTime } from '../../utils/formatting';
import type { Machine, MachineAlias } from './types';

export function MachinesPage({ workspace }: { workspace: Workspace }) {
  const client = useQueryClient(); const machines = useQuery<Machine[]>({ queryKey: ['machines', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/machines`), refetchInterval: 15_000 });
  const remove = useMutation({ mutationFn: (alias: MachineAlias) => api(`/workspaces/${workspace.id}/repositories/${alias.repositoryId}/aliases/${alias.id}`, mutation('DELETE')), onSuccess: () => client.invalidateQueries({ queryKey: ['machines', workspace.id] }) });
  const now = Date.now();
  return <Page heading="Machines & aliases" subheading="Shared checkout identities, active work, leases, synchronization, and repository path mappings."><div className="machine-list">{machines.isLoading ? <p className="muted">Loading machine coordination…</p> : machines.data?.map((machine) => { const age = machine.lastSeenAt ? now - Date.parse(machine.lastSeenAt) : Infinity; const state = age < 5 * 60_000 ? 'online' : age < 24 * 60 * 60_000 ? 'stale' : 'offline'; return <article key={machine.machineIdentity} className="machine-card"><header><div><h2>{machine.machineIdentity}</h2><p>Last seen {machine.lastSeenAt ? relativeTime(machine.lastSeenAt) : 'never'}</p></div><span className={`machine-state ${state}`}>{state}</span></header><div className="fact-strip"><div><small>Active task</small><strong>{machine.activeTask?.identifier ?? 'None'}</strong></div><div><small>Active run</small><strong>{machine.activeRun?.id.slice(0, 8) ?? 'None'}</strong></div><div><small>Leases</small><strong>{machine.leases.length}</strong></div><div><small>Last sync</small><strong>{machine.lastSyncAt ? relativeTime(machine.lastSyncAt) : 'Not reported'}</strong></div></div><section><h3>Repository aliases</h3>{machine.aliases.length ? machine.aliases.map((alias) => <div className="alias-row" key={alias.id}><strong>{alias.repository.fullName}</strong><code>{alias.localPath}</code><small>{relativeTime(alias.updatedAt)}</small>{workspace.role !== 'member' ? <button className="text-button danger" disabled={remove.isPending} onClick={() => window.confirm(`Remove ${alias.localPath}?`) && remove.mutate(alias)}>Remove</button> : null}</div>) : <p className="muted">No checkout paths registered.</p>}</section>{machine.leases.length ? <section><h3>Active leases</h3>{machine.leases.map((lease) => <div className="alias-row" key={lease.id}><strong>{lease.task.identifier}</strong><span>{lease.writeAccess ? 'Write' : 'Read'} · {lease.activity}</span><code>{lease.pathScope.join(', ') || 'all paths'}</code></div>)}</section> : null}</article>; })}</div></Page>;
}
