import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api, mutation, type Workspace } from '../../api';

const evidenceTypes = ['transcript', 'tool_output', 'terminal_log', 'patch', 'build_report', 'test_result', 'screenshot', 'document', 'dependency_snapshot', 'native_session_archive', 'other'];
const toBase64 = (bytes: Uint8Array) => { let value = ''; for (let index = 0; index < bytes.length; index += 0x8000) value += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(value); };
const sha256 = async (bytes: Uint8Array) => [...new Uint8Array(await crypto.subtle.digest('SHA-256', bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer))].map((entry) => entry.toString(16).padStart(2, '0')).join('');

export function EvidenceComposer({ workspace, taskId }: { workspace: Workspace; taskId?: string }) {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [mode, setMode] = useState<'text' | 'file'>('text'); const [file, setFile] = useState<File | null>(null); const [text, setText] = useState(''); const [hash, setHash] = useState(''); const [form, setForm] = useState({ title: '', type: 'document', producer: 'anklav-web', mimeType: 'text/plain', preview: '', redactionStatus: 'unreviewed', retentionPolicy: 'project_default', taskId: taskId ?? '', runId: '', runEventId: '' });
  const record = useMutation({ mutationFn: async () => { const bytes = mode === 'file' && file ? new Uint8Array(await file.arrayBuffer()) : new TextEncoder().encode(text); const claimedHash = hash || await sha256(bytes); return api(`/workspaces/${workspace.id}/evidence-artifacts`, mutation('POST', { ...form, taskId: form.taskId || undefined, runId: form.runId || undefined, runEventId: form.runEventId || undefined, mimeType: mode === 'file' && file ? file.type || 'application/octet-stream' : form.mimeType, contentBase64: toBase64(bytes), claimedHash, idempotencyKey: `web:${crypto.randomUUID()}` })); }, onSuccess: (artifact: any) => { setHash(artifact.contentHash); setOpen(false); client.invalidateQueries({ queryKey: ['evidence', workspace.id] }); client.invalidateQueries({ queryKey: ['evidence', workspace.id, taskId ?? 'all'] }); } });
  return <section className="evidence-create"><button className="button primary" onClick={() => setOpen((value) => !value)}>Record evidence</button>{open ? <div className="evidence-form"><div className="control-tabs"><button className={mode === 'text' ? 'active' : ''} onClick={() => setMode('text')}>Text</button><button className={mode === 'file' ? 'active' : ''} onClick={() => setMode('file')}>File upload</button></div><label>Title<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Type<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}>{evidenceTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>Producer<input value={form.producer} onChange={(event) => setForm({ ...form, producer: event.target.value })} /></label>{mode === 'text' ? <label>Exact text<textarea value={text} onChange={(event) => setText(event.target.value)} /></label> : <label>Exact file<input type="file" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label>}<label>Safe preview<textarea value={form.preview} onChange={(event) => setForm({ ...form, preview: event.target.value })} /></label><div className="form-grid"><label>Redaction<select value={form.redactionStatus} onChange={(event) => setForm({ ...form, redactionStatus: event.target.value })}><option>unreviewed</option><option>redacted</option><option>contains_sensitive</option></select></label><label>Retention<input value={form.retentionPolicy} onChange={(event) => setForm({ ...form, retentionPolicy: event.target.value })} /></label><label>Task ID<input value={form.taskId} onChange={(event) => setForm({ ...form, taskId: event.target.value })} /></label><label>Run ID<input value={form.runId} onChange={(event) => setForm({ ...form, runId: event.target.value })} /></label><label>Event ID<input value={form.runEventId} onChange={(event) => setForm({ ...form, runEventId: event.target.value })} /></label><label>Claimed SHA-256 (optional)<input value={hash} onChange={(event) => setHash(event.target.value)} /></label></div>{record.error ? <p className="error">{record.error.message}</p> : null}<button className="button primary" disabled={!form.title || (mode === 'text' ? !text : !file) || record.isPending} onClick={() => record.mutate()}>{record.isPending ? 'Verifying and recording…' : 'Verify hash & record'}</button></div> : null}{hash && !open ? <p className="success">Evidence stored and verified as <code>{hash}</code>.</p> : null}</section>;
}
