import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api, type Workspace } from '../../api';
import { Empty } from '../../components/molecules/Empty';
import { relativeTime } from '../../utils/formatting';
import { formatEvidenceSize } from './formatEvidenceSize';
import type { EvidenceArtifact, EvidenceRow } from './types';

export function EvidenceBrowser({ workspace, taskId }: { workspace: Workspace; taskId?: string }) {
  const [selectedId, setSelectedId] = useState(''); const [query, setQuery] = useState(''); const [type, setType] = useState(''); const [redaction, setRedaction] = useState('');
  const rows = useQuery<EvidenceRow[]>({ queryKey: ['evidence', workspace.id, taskId ?? 'all'], queryFn: () => api(`/workspaces/${workspace.id}/evidence-artifacts${taskId ? `?taskId=${encodeURIComponent(taskId)}` : ''}`) });
  const items = useMemo(() => (rows.data ?? []).map((row) => ({ ...row.artifact, byteSize: row.blob.byteSize, contentHash: row.blob.hash, verifiedAt: row.blob.verifiedAt })), [rows.data]);
  const types = [...new Set(items.map((item) => item.type))].sort();
  const filtered = items.filter((item) => (!query || `${item.title} ${item.type} ${item.producer}`.toLowerCase().includes(query.toLowerCase())) && (!type || item.type === type) && (!redaction || item.redactionStatus === redaction));
  const selected = filtered.find((item) => item.id === selectedId) ?? filtered[0];
  const detail = useQuery<EvidenceArtifact>({ queryKey: ['evidence-detail', workspace.id, selected?.id], queryFn: () => api(`/workspaces/${workspace.id}/evidence-artifacts/${selected!.id}`), enabled: Boolean(selected?.id) });
  const artifact = detail.data ?? selected;
  if (!rows.isLoading && !items.length) return <Empty title="No exact evidence yet" text="Evidence captured by runs, checkpoints, and verification will appear here with immutable hashes." />;
  return <div className="control-workbench evidence-workbench"><aside className="control-list"><div className="control-toolbar"><input aria-label="Search evidence" placeholder="Search evidence…" value={query} onChange={(event) => setQuery(event.target.value)} /><div className="control-filters"><select aria-label="Evidence type" value={type} onChange={(event) => setType(event.target.value)}><option value="">All types</option>{types.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Redaction status" value={redaction} onChange={(event) => setRedaction(event.target.value)}><option value="">All visibility</option><option value="unredacted">Unredacted</option><option value="redacted">Redacted</option><option value="withheld">Withheld</option></select></div></div><div className="control-list-heading"><span>{filtered.length} artifacts</span><span>Newest first</span></div><div className="control-rows">{filtered.map((item) => <button key={item.id} className={`control-row ${item.id === artifact?.id ? 'selected' : ''}`} onClick={() => setSelectedId(item.id)}><span className="artifact-glyph">{item.mimeType.startsWith('image/') ? '▧' : item.type.includes('patch') ? '±' : '≡'}</span><span><strong>{item.title}</strong><small>{item.type.replaceAll('_', ' ')} · {formatEvidenceSize(item.byteSize)}</small></span><time>{relativeTime(item.createdAt)}</time></button>)}</div></aside>
    <section className="control-detail">{artifact ? <><header className="control-detail-header"><div><span className="eyebrow">{artifact.type.replaceAll('_', ' ')}</span><h2>{artifact.title}</h2><p>{artifact.mimeType} · {formatEvidenceSize(artifact.byteSize)}</p></div><a className="button primary" href={`/api/v1/workspaces/${workspace.id}/evidence-artifacts/${artifact.id}/content`}>Download exact file</a></header><div className="fact-strip"><div><small>Integrity</small><strong>{artifact.verifiedAt ? 'Verified' : 'Stored'}</strong></div><div><small>Visibility</small><strong>{artifact.redactionStatus}</strong></div><div><small>Retention</small><strong>{artifact.retentionPolicy}</strong></div><div><small>Producer</small><strong>{artifact.producer}</strong></div></div><section className="inspector-section"><div className="section-header"><h3>Safe preview</h3><small>{artifact.preview ? 'Stored preview' : 'No preview retained'}</small></div>{artifact.preview ? <pre className="evidence-preview">{artifact.preview}</pre> : <p className="muted">Preview omitted. Download the exact artifact to inspect its authenticated bytes.</p>}</section><section className="inspector-section"><h3>Provenance</h3><dl className="inspector-dl"><div><dt>Project</dt><dd>{artifact.projectId ?? '—'}</dd></div><div><dt>Task</dt><dd>{artifact.taskId ?? '—'}</dd></div><div><dt>Run</dt><dd>{artifact.runId ?? '—'}</dd></div><div><dt>Produced</dt><dd>{new Date(artifact.createdAt).toLocaleString()}</dd></div></dl></section><section className="inspector-section"><h3>Integrity record</h3><dl className="inspector-dl"><div><dt>SHA-256</dt><dd><code>{artifact.contentHash}</code></dd></div><div><dt>Artifact ID</dt><dd><code>{artifact.id}</code></dd></div>{artifact.producingRunEventIds?.map((id) => <div key={id}><dt>Run event</dt><dd><code>{id}</code></dd></div>)}</dl></section></> : <Empty title="Select evidence" text="Choose an artifact to inspect its provenance and integrity record." />}</section></div>;
}
