import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api, ApiError, mutation, type Workspace } from '../../api';
import type { Run } from './taskRunsTypes';

export function RunAdministration({ workspace, taskId, run }: { workspace: Workspace; taskId: string; run?: Run | null }) {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [machine, setMachine] = useState('browser:manual'); const [summary, setSummary] = useState('');
  const refresh = () => { client.invalidateQueries({ queryKey: ['task-runs', workspace.id, taskId] }); client.invalidateQueries({ queryKey: ['task-operations', workspace.id, taskId] }); client.invalidateQueries({ queryKey: ['task-leases', workspace.id, taskId] }); };
  const start = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/tasks/${taskId}/runs`, mutation('POST', { provider: 'human', client: 'anklav-web', agentType: 'manual', machineIdentity: machine, modifiesCode: false, permissions: { initiatedFrom: 'web' } })), onSuccess: () => { setOpen(false); refresh(); } });
  const finish = useMutation({ mutationFn: (status: string) => api(`/workspaces/${workspace.id}/runs/${run!.id}/finish`, mutation('POST', { status, outcomeSummary: summary, tokenUsage: {} })), onSuccess: refresh });
  const lease = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/runs/${run!.id}/lease`, mutation('POST', { activity: summary || 'Manual browser coordination', writeAccess: false, exclusive: false, pathScope: [], ttlSeconds: 900 })), onSuccess: refresh });
  const checkpoint = useMutation({ mutationFn: () => api(`/workspaces/${workspace.id}/runs/${run!.id}/checkpoints`, mutation('POST', { objective: summary || 'Manual checkpoint', summary: summary || 'Checkpoint created from the task operations panel.', completedWork: [], remainingWork: [], activeDecisionIds: [], relevantPaths: [], failures: [], lastVerified: {}, nextAction: 'Continue from this manually recorded checkpoint.', artifactIds: [], evidenceArtifactIds: [], assumptions: [] })), onSuccess: refresh });
  const error = start.error ?? finish.error ?? lease.error ?? checkpoint.error;
  return <div className="run-admin"><button className="button primary" onClick={() => setOpen((value) => !value)}>Start manual run</button>{open ? <div className="inline-admin-form"><label>Machine identity<input value={machine} onChange={(event) => setMachine(event.target.value)} /></label><button className="button" disabled={!machine.trim() || start.isPending} onClick={() => start.mutate()}>Start read-only run</button></div> : null}{run?.status === 'running' ? <><input aria-label="Operational note" value={summary} onChange={(event) => setSummary(event.target.value)} placeholder="Outcome, lease activity, or checkpoint summary…" /><button className="button" onClick={() => lease.mutate()}>Claim read lease</button><button className="button" onClick={() => checkpoint.mutate()}>Checkpoint</button><button className="button" onClick={() => finish.mutate('completed')}>Finish</button><button className="button danger" onClick={() => window.confirm('Cancel this run?') && finish.mutate('cancelled')}>Cancel</button><button className="text-button danger" onClick={() => window.confirm('Mark this stranded run failed?') && finish.mutate('failed')}>Abandon</button></> : null}{error ? <p className="error">{error instanceof ApiError ? error.message : 'Operation failed.'}</p> : null}</div>;
}
