import { useQuery } from '@tanstack/react-query';
import { api } from '../../api';
import type { Page as ApiPage, Project, Workspace } from '../../api';
import { Field } from '../../components/atoms/Field';
import { healthOptions } from '../../utils/healthOptions';
import { priorityOptions } from '../../utils/priorityOptions';

export function TaskProperties({ workspace, task, save }: { workspace: Workspace; task: any; save: (body: any) => void }) {
  const projects = useQuery<ApiPage<Project>>({ queryKey: ['project-options', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/projects?limit=100`) }); const flows = useQuery<ApiPage<any>>({ queryKey: ['flow-options', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/flows?limit=100`) }); const members = useQuery<any[]>({ queryKey: ['members', workspace.id], queryFn: () => api(`/workspaces/${workspace.id}/members`) });
  const primaryFlowId = task.flows?.find((entry: any) => entry.link.role === 'primary')?.flow.id ?? ''; const relatedFlowIds = task.flows?.filter((entry: any) => entry.link.role === 'related').map((entry: any) => entry.flow.id) ?? [];
  return <details className="properties"><summary>Manage task</summary><form className="property-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); save({ title: form.get('title'), projectId: form.get('projectId'), priority: form.get('priority'), assigneeMembershipId: form.get('assigneeMembershipId') || null, dueDate: form.get('dueDate') || null, humanReviewRequired: form.get('humanReviewRequired') === 'on', reviewerMembershipId: form.get('reviewerMembershipId') || null, primaryFlowId: form.get('primaryFlowId') || null, relatedFlowIds: Array.from((event.currentTarget.elements.namedItem('relatedFlowIds') as HTMLSelectElement).selectedOptions).map((option) => option.value) }); }}><Field label="Title" name="title" defaultValue={task.title} required /><label>Project<select name="projectId" defaultValue={task.projectId}>{projects.data?.items.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Priority<select name="priority" defaultValue={task.priority}>{priorityOptions()}</select></label><label>Assignee<select name="assigneeMembershipId" defaultValue={task.assigneeMembershipId ?? ''}><option value="">Unassigned</option>{members.data?.filter((member) => member.active).map((member) => <option key={member.id} value={member.id}>{member.displayName}</option>)}</select></label><Field label="Due date" name="dueDate" type="date" defaultValue={task.dueDate ?? ''} /><label className="check"><input name="humanReviewRequired" type="checkbox" defaultChecked={task.humanReviewRequired} />Human review required</label><label>Reviewer<select name="reviewerMembershipId" defaultValue={task.reviewerMembershipId ?? ''}><option value="">No reviewer</option>{members.data?.filter((member) => member.active).map((member) => <option key={member.id} value={member.id}>{member.displayName}</option>)}</select></label><label>Primary flow<select name="primaryFlowId" defaultValue={primaryFlowId}><option value="">No primary flow</option>{flows.data?.items.map(({ flow }) => <option key={flow.id} value={flow.id}>{flow.name}</option>)}</select></label><label>Related flows<select name="relatedFlowIds" multiple defaultValue={relatedFlowIds}>{flows.data?.items.map(({ flow }) => <option key={flow.id} value={flow.id}>{flow.name}</option>)}</select></label><button className="button primary" type="submit">Save task details</button></form></details>;
}
